# Generated by Django 4.0.6 on 2024-04-15 05:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Personal_Data', '0005_alter_personal_file_din_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIN_KYC_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KYC_date', models.DateField(default=datetime.date(2024, 4, 15))),
                ('KYC_year', models.IntegerField(default=2024)),
                ('KYC_proof', models.FileField(blank=True, null=True, upload_to='reporting_file')),
                ('Remarks', models.CharField(max_length=300)),
                ('din_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='din_access', to='Personal_Data.personal_file', to_field='din_no')),
            ],
        ),
    ]
