# Generated by Django 4.0.6 on 2024-04-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting_Data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='din_kyc_file',
            name='din_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
