# Generated by Django 4.0.6 on 2024-04-17 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting_Data', '0004_alter_din_kyc_file_kyc_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTEC_no_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTEC_no', models.IntegerField(unique=True)),
                ('PTEC_date', models.DateField(default=datetime.date(2024, 4, 17))),
                ('PTEC_year', models.IntegerField(default=2024)),
                ('PTEC_proof', models.FileField(blank=True, null=True, upload_to='reporting_file')),
                ('Remarks', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='din_kyc_file',
            name='KYC_date',
            field=models.DateField(default=datetime.date(2024, 4, 17)),
        ),
    ]
