# Generated by Django 4.0.6 on 2024-04-23 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting_Data', '0005_ptec_no_file_alter_din_kyc_file_kyc_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTRC_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTRC_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='din_kyc_file',
            name='KYC_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ptec_no_file',
            name='PTEC_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PTRC_no_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PTRC_year', models.IntegerField(default=2024)),
                ('PTRC_month', models.IntegerField(default=4)),
                ('PTRC_date', models.DateField(default=django.utils.timezone.now)),
                ('PTRC_proof', models.FileField(blank=True, null=True, upload_to='reporting_file')),
                ('Remarks', models.CharField(max_length=300)),
                ('PTRC_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reporting_Data.ptrc_no')),
            ],
        ),
    ]
