# Generated by Django 4.0.6 on 2024-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reporting_Data', '0006_ptrc_no_alter_din_kyc_file_kyc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptrc_no_file',
            name='PTRC_month',
            field=models.IntegerField(default=5),
        ),
    ]
