# Generated by Django 4.0.6 on 2024-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Data', '0002_personal_file_ptec_personal_file_ptec_no_and_more'),
        ('Company_Data', '0002_company_file_ptec_company_file_ptec_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_file',
            name='director_partner_list',
        ),
        migrations.AddField(
            model_name='company_file',
            name='director_partner_list',
            field=models.ManyToManyField(to='Personal_Data.personal_file'),
        ),
    ]
