# Generated by Django 4.0.6 on 2024-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_file',
            fields=[
                ('code_no', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('passport_size_photo', models.FileField(blank=True, null=True, upload_to='personal_file')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='personal_file')),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to='personal_file')),
                ('passport', models.FileField(blank=True, null=True, upload_to='personal_file')),
                ('driving_licence', models.FileField(blank=True, null=True, upload_to='personal_file')),
                ('gst', models.FileField(blank=True, null=True, upload_to='personal_file')),
                ('Remarks', models.CharField(max_length=300)),
            ],
        ),
    ]
