# Generated by Django 4.0.6 on 2024-03-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_file',
            name='PTEC',
            field=models.FileField(blank=True, null=True, upload_to='personal_file'),
        ),
        migrations.AddField(
            model_name='personal_file',
            name='PTEC_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='aadhar_card_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='din',
            field=models.FileField(blank=True, null=True, upload_to='personal_file'),
        ),
        migrations.AddField(
            model_name='personal_file',
            name='din_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='driving_licence_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='gst_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='pan_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal_file',
            name='passport_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
