# Generated by Django 4.0.6 on 2024-04-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Data', '0002_personal_file_ptec_personal_file_ptec_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_file',
            name='din_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
